par(mfrow = c(2, 2))
plot(econsumption$NDate,econsumption$Global_active_power, ylab = "Global Active Power", type = 'l',xlab = "", main = "")
plot(econsumption$NDate,econsumption$Voltage, ylab = "Voltage", type = 'l',xlab = "datetime", main = "")
plot(econsumption$NDate,econsumption$Sub_metering_1, ylab = "Energy sub meterin", type = 'l',xlab = "")
points(econsumption$NDate,econsumption$Sub_metering_2, col="red", type = 'l')
points(econsumption$NDate,econsumption$Sub_metering_3, col="blue", type = 'l')
plot(econsumption$NDate,econsumption$Global_reactive_power, type = 'l',xlab = "datetime", ylab = "Global_reactive_power", main = "")
dev.copy(png, file = "plot4.png", width= 480, height= 480, units = "px") 
dev.off() 